### ISSUE TITLE
Failed to load private key

### ISSUE THREAD

**Issue by SebastianRehfeldt** [mawendo-gmbh/secon-keystore-generator#2]
Hey, I was trying to create the certificate file required to run the `diga-api-client` by @fongie and run into an error loading the private key file. Our private key looks like the following and results in `Must provide a PKCS1 file (starting with BEGIN RSA PRIVATE KEY)`.

```
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

Adding the missing ` RSA` to the header/footer line in the private key file resulted in a `SeconKeyStoreGeneratorException: Failed to create keystore`  caused by an `InvalidKeySpecException` in the `PrivateKeyHandler` class.

The private key was already sent to ITSG and we received the chain file. Therefore, I needed to get it working with the key we already created. What finally made it is creating a raw PKCS#8 file using the following command

```bash
openssl pkcs8 -topk8 -inform PEM -outform DER -in my.prv.key.pem -out my.prv.key.der -nocrypt
```

And then use the [readPkcs8PrivateKey method](https://github.com/Mastercard/client-encryption-java/blob/master/src/main/java/com/mastercard/developer/utils/EncryptionUtils.java#L82) from the mastercard `EncryptionUtils` instead of `readPkcs1PrivateKey`. This successfully created the `certificates.p12` file which can be used in the `diga-api-client`.

If you think it's helpful I can open a PR to add the possibility to load private keys in `PKCS#8` format.

**Comment by SebastianRehfeldt** [comment]
Hi @fongie and @michaelmerg ,
I opened a PR to address the issue that we were experiencing with generating the keychain file for the `diga-api-client`. Would you be up for having a look at the proposed changes? :)

**Comment by michaelmerg** [comment]
Hi @SebastianRehfeldt,

the PR looks good to me, thank you for the contribution. Sorry I didn't have the time to try it out. I hope I can try it this week and merge it.

**Comment by SebastianRehfeldt** [comment]
Sounds good! :)
And big thanks for providing this tool in the first place.

**Comment by fongie** [comment]
nice job @SebastianRehfeldt! I am happy to see improvements on keystore generation, as that actually felt like a major hurdle to get past in this process of integrating with the diga api :)

**Comment by SebastianRehfeldt** [comment]
Thanks @fongie ! I must admit that I was a bit afraid we have to go through the whole ITSG certification again after the keychain generation using this tool failed for our private key. Therefore I am also very happy it's working now 😆
